"""baseline current schema

Revision ID: 88e01695750a
Revises: 
Create Date: 2026-08-17 12:22:30.478560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88e01695750a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_dates',
    sa.Column('bd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bd_date', sa.Date(), nullable=False),
    sa.Column('bd_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('bd_id')
    )
    with op.batch_alter_table('blocked_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_dates_bd_date'), ['bd_date'], unique=True)

    op.create_table('bookers',
    sa.Column('booker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booker_name', sa.String(length=100), nullable=False),
    sa.Column('booker_email', sa.String(length=120), nullable=False),
    sa.Column('booker_phone', sa.String(length=30), nullable=True),
    sa.Column('booker_date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('booker_id')
    )
    with op.batch_alter_table('bookers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookers_booker_email'), ['booker_email'], unique=False)

    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donation_name', sa.String(length=100), nullable=True),
    sa.Column('donation_email', sa.String(length=120), nullable=True),
    sa.Column('donation_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('donation_currency', sa.String(length=10), nullable=False),
    sa.Column('donation_gateway', sa.Enum('paystack', 'stripe'), nullable=False),
    sa.Column('donation_transaction_reference', sa.String(length=120), nullable=True),
    sa.Column('donation_status', sa.Enum('pending', 'completed', 'failed', 'refunded'), nullable=False),
    sa.Column('donation_is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('donation_date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('donation_id'),
    sa.UniqueConstraint('donation_transaction_reference')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_donation_date_added'), ['donation_date_added'], unique=False)

    op.create_table('recurring_series',
    sa.Column('series_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_frequency', sa.Enum('weekly', 'biweekly', 'monthly'), nullable=False),
    sa.Column('series_start_date', sa.Date(), nullable=False),
    sa.Column('series_end_date', sa.Date(), nullable=False),
    sa.Column('series_date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('recurring_unavailability',
    sa.Column('ru_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ru_day_of_week', sa.Integer(), nullable=False),
    sa.Column('ru_start_time', sa.Time(), nullable=False),
    sa.Column('ru_end_time', sa.Time(), nullable=False),
    sa.Column('ru_reason', sa.String(length=255), nullable=True),
    sa.Column('ru_date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ru_id')
    )
    op.create_table('working_hours',
    sa.Column('wh_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wh_day_of_week', sa.Integer(), nullable=False),
    sa.Column('wh_start_time', sa.Time(), nullable=False),
    sa.Column('wh_end_time', sa.Time(), nullable=False),
    sa.Column('wh_is_active', sa.Boolean(), nullable=True),
    sa.Column('wh_updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('wh_id'),
    sa.UniqueConstraint('wh_day_of_week')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booker_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_start_time', sa.Time(), nullable=False),
    sa.Column('booking_end_time', sa.Time(), nullable=False),
    sa.Column('booking_session_type', sa.Enum('video', 'audio'), nullable=False),
    sa.Column('booking_session_format', sa.Enum('single', 'recurring'), nullable=False),
    sa.Column('booking_status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', 'no_show', 'rescheduled'), nullable=False),
    sa.Column('booking_manage_token', sa.String(length=36), nullable=False),
    sa.Column('booking_meet_link', sa.String(length=255), nullable=True),
    sa.Column('booking_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('booking_reason', sa.Text(), nullable=True),
    sa.Column('booking_notes', sa.Text(), nullable=True),
    sa.Column('booking_date_added', sa.DateTime(), nullable=True),
    sa.Column('booking_updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booker_id'], ['bookers.booker_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['recurring_series.series_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booker_id'), ['booker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_manage_token'), ['booking_manage_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_series_id'), ['series_id'], unique=False)

    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_counters_expires_at')

    op.drop_table('rate_limit_counters')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_flyer_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_flyer_filename')

    op.create_table('rate_limit_counters',
    sa.Column('key_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('counter_key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_counters_expires_at', ['expires_at'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_series_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_manage_token'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))
        batch_op.drop_index(batch_op.f('ix_bookings_booker_id'))

    op.drop_table('bookings')
    op.drop_table('working_hours')
    op.drop_table('recurring_unavailability')
    op.drop_table('recurring_series')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_donation_date_added'))

    op.drop_table('donations')
    with op.batch_alter_table('bookers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookers_booker_email'))

    op.drop_table('bookers')
    with op.batch_alter_table('blocked_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_dates_bd_date'))

    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
